### PR TITLE
Update base URL

### PR DESCRIPTION
**Pull request by bootstraponline**

### CODE REVIEW

**Comment by prfarlow1** [comment]
@trapacska When can we expect this PR to be merged in and released? This bitrise step is failing 100% of the time right now and we need this fix

**Comment by viplezer** [comment]
The baseURL is still unchanged in main_test.go. Otherwise @trapacska please merge this ASAP

**Comment by bootstraponline** [comment]
Updated!

**Comment by bootstraponline** [comment]
Why is the bitrise job failing? I click on the link and see:

**Comment by godrei** [comment]
Hi @bootstraponline , thanks for the PR.

The CI was failing since:
- the iOS sample app had codesigning issues, fixed in this commit: https://github.com/bitrise-steplib/bitrise-step-flank/pull/5/commits/fd2e1883cc2d175045c43bef4e92bd0a546e3a95
- there was an issue in the flank download URL builder logic: the latest Flank release's tag: `v20.05.1`, the findLatestVersion function trimmed the minor version component's leading `0`, so it produced an invalid download URL: 

```
Failed to download binary, error: http GET https://github.com/Flank/[REDACTED]/releases/download/v20.5.1/[REDACTED].jar non success status code: 404
``` 

see the new test case: https://github.com/bitrise-steplib/bitrise-step-flank/pull/5/commits/5b9835bd373316d58bcb86e22250c9543912188a

**Review by trapacska — APPROVED** [review]

**Comment by bootstraponline** [comment]
Thanks!

**Pull request merged**
